language: node_js

dist: trusty
sudo: false

node_js:
  - 'node'
  - '10'
  - '8'

install:
  - yarn

script:
  - yarn global add codecov
  - yarn run test
  - mv coverage/coverage-final.json coverage/coverage.json
  - codecov
  - npx gulp build

deploy:
  provider: lambda
  function-name: "emwas"
  region: "eu-west-3"
  role: "arn:aws:iam::226859925527:role/service-role/emwas-role-hejdd6z9"
  handler_name: "lambda.handler"
  on:
    branch: master
    node: '8'