language: node_js

dist: trusty
sudo: false

node_js:
  - 'node'
  - '10'
  - '8'

install:
  - yarn

script:
  - yarn global add codecov
  - yarn run test
  - mv coverage/coverage-final.json coverage/coverage.json
  - codecov
  - npx gulp build
