language: node_js

dist: trusty
sudo: false

addons:
  sonarcloud:
    organisation: fabienleite-github
    token:
      secure: $SONAR_TOKEN

node_js:
  - 'node'
  - 10

install:
  - npm install --dev

script:
  - npm test
  - npm run codecov
  - sonar-scanner
