#%RAML 1.0
title: Poogle
description: "Poogle is a meta search engine that gather searches from different porn sites and display them into one only convivial interface. It allows you to find the porn you're looking for faster and gives you the direct link to the original videos. It is for now intended to work with a limited number of non-free big porn websites."
version: v1
/user:
  get:
    description: Get the list of all the users of the system
    responses:
      200:
        body:
          application/json:
            example: !include examples/user/users.json
      500:
        body:
          application/json:
            example: !include examples/errors/serverError.json

  post:
    description: Add a new user
    queryParameters:
      email:
        type: string
      userName:
        type: string
      receivesNews:
        type: boolean
        default: false
        description: Whether or not the user receives news about the service (updates, improvements, ...)
        required: false
      services:
        required: false
        type: array
        description: Array of services id.
    responses:
      200:
        body:
          application/json:
            example: !include examples/user/addUser.json
      400:
        body:
          application/json:
            examples:
              badParameter: !include examples/errors/badRequest.json
              emailTaken: !include examples/user/emailTaken.json
      500:
        body:
          application/json:
            example: !include examples/errors/serverError.json

/services:
  get:
    description: Get all the currently availables services in the API
    responses:
      200:
        body:
          application/json:
            example: !include examples/services/services.json
      500:
        body:
          application/json:
            example: !include examples/errors/serverError.json

/search:
  get:
    description: Performs a search on all the user's activated services
